database:
  use-mysql: false
  host: 'HOST'
  port: 'PORT'
  database: 'DATABASE'
  username: 'USERNAME'
  password: 'PASSWORD'
cosmetics:
  guitar:
    name: 'Гитара'
    customModelData: 1000
    position: BODY
    material: structure_void
